// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientData = { color_hue: number, id: number, instrument_name: string, };

/**
 * Represents a message sendable by the client
 */
export type ClientMessage = { "type": "Play", note: string, volume: number, } | { "type": "Stop", note: string, sustain: boolean, } | { "type": "InstrumentChange", instrument_name: string, };

/**
 * Represents a message sendable by the server
 */
export type ServerMessage = { "type": "Error", error: string, } | { "type": "ClientConnect" } & ClientData | { "type": "ReceiveInfo", client_list: Array<ClientData>, created_client: ClientData, } | { "type": "ClientDisconnect", id: number, } | { "type": "Relay", msg: ClientMessage, id: number, };
