name: Building, Testing and Deployment

on: [push, pull_request]

jobs:
    build-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build frontend
              working-directory: ./frontend
              run: yarn && echo "BACKEND_HOST=http://localhost:3000" > ./.env && yarn build
            - name: Build backend
              working-directory: ./backend
              run: yarn && yarn build
            - name: Test run backend
              working-directory: ./backend
              run: yarn start & sleep 5; kill $!

    deploy:
        needs: build-test
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository_owner == 'Calbabreaker'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build frontend with actual server env
              working-directory: ./frontend
              run: yarn && echo "BACKEND_HOST=https://piano-backend.herokuapp.com" > ./.env && yarn build && ls -lah public
            - name: Build backend
              working-directory: ./backend
              run: yarn && yarn build && rm -fr node_modules/
            # - name: Push deploy-frontend
            #   uses: s0/git-publish-subdir-action@develop
            #   env:
            #       REPO: self
            #       BRANCH: deploy-frontend
            #       FOLDER: frontend/public
            #       MESSAGE: "Deploy at {sha}"
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # - name: Push deploy-backend
            #   uses: s0/git-publish-subdir-action@develop
            #   env:
            #       REPO: self
            #       BRANCH: deploy-backend
            #       FOLDER: backend
            #       MESSAGE: "Deploy at {sha}"
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
